apiVersion: v1
kind: Service
metadata:
  name: thanos-receive-router
  namespace: thanos
spec:
  ports:
  - name: grpc
    port: 10901
  - name: http
    port: 10902
  - name: remote-write
    port: 19291
  selector:
    app.kubernetes.io/component: thanos-receive-router
    app.kubernetes.io/instance: thanos-receive
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.22.0
