apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: thanos-store
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: v0.10.1
  name: thanos-store
  namespace: thanos
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: thanos-store
      app.kubernetes.io/instance: thanos-store
      app.kubernetes.io/name: thanos
