apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: database-write-hashring
    app.kubernetes.io/instance: thanos-receive-ingestor
    app.kubernetes.io/name: thanos-receive
    app.kubernetes.io/version: v0.31.0
  name: thanos-receive-ingestor
  namespace: thanos
