apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: object-store-bucket-debugging
    app.kubernetes.io/instance: thanos-bucket
    app.kubernetes.io/name: thanos-bucket
    app.kubernetes.io/version: v0.22.0
  name: thanos-bucket
  namespace: thanos
