apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: thanos-receive-default
  namespace: thanos
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: database-write-hashring
      app.kubernetes.io/instance: thanos-receive-default
      app.kubernetes.io/name: thanos-receive
      controller.receive.thanos.io/hashring: default
